name: Update code at AWS

on:
  pull_request:
    types: [ closed ]


jobs:
  deploy:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install serverless
        run: |
          npm install -g serverless
          serverless plugin install -n serverless-plugin-warmup
          serverless plugin install -n serverless-python-requirements
      - name: serverless deploy
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
